### ISSUE TITLE
a new release per the project rename?

### ISSUE THREAD

**Issue by chenrui333** [cabinpkg/cabin#1053]
👋 when [bumping the revision for poac formula per fmt version bump](https://github.com/Homebrew/homebrew-core/pull/202565), I noticed some checksum mismatch for 0.10.1 release (did not see it before for the other project rename).

With that being said, maybe cut a new release for the project rename?

Thanks!

**Comment by ken-matsui** [comment]
Hmm, that's unexpected, but yes, will do. I'll let you know once it's done.

**Comment by ken-matsui** [comment]
Done, https://github.com/cabinpkg/cabin/releases/tag/0.11.0. Thanks!

**Comment by chenrui333** [comment]
Thanks @ken-matsui!

---

relates to https://github.com/Homebrew/homebrew-core/pull/202655
